### PR TITLE
Prop spawner

### PR DESCRIPTION
**Pull request by BombayV**
added a space for prop's and added a few props animations

### CODE REVIEW

**Comment by BombayV** [comment]
@Branqueador Do you mind pushing only your changes? It seems like you uploaded the who anims resource which makes it a pain to read what you actually changed.

**Comment by Branqueador** [comment]
@BombayV can you please have a look now? i think it's done the way you wanted
https://github.com/Branqueador/anims

**Comment by BombayV** [comment]
Yep, I'll delete this PR.

**Comment by BombayV** [comment]
@Branqueador Open a new one.

**Pull request closed without merging**
