### PR TITLE
/e [emote] command added.

### PR DESCRIPTION
**Pull request by xDope7137**

### CODE REVIEW

**Comment by BombayV** [comment]
Please follow the same format as the /emote command. Apart from that, the new command should be under the /emote command.

**Comment by xDope7137** [comment]
I think there is no /emote command. There is a chat suggestion added for /e but no obvious code where it links command with a  function to play the emote.

https://github.com/BombayV/anims/blob/ab815bc2a3f67ee0dc1a020a538593fb65976c84/client/request.lua#L222

People are used to /e in every server that is why /e was added. 

There is a suggestion for /e right here, https://github.com/BombayV/anims/blob/ab815bc2a3f67ee0dc1a020a538593fb65976c84/cfg.lua#L5

**Comment by BombayV** [comment]
https://github.com/BombayV/anims/blob/main/client/nui.lua#L159
Follow the same format as this command.

**Comment by xDope7137** [comment]
Oh shit I might have accidentally removed the command while working on it that is why I opened PR. My bad

**Pull request closed without merging**
