### PR TITLE
New anims

### PR DESCRIPTION
**Pull request by icecubepiso**
i added some anims from ultra hackx and some from DivineDude or.. idk what his name is

### CODE REVIEW

**Comment by BombayV** [comment]
Hey, thank you very much. Could you add a link to where you the gang signs animations from?

**Comment by icecubepiso** [comment]
ye, no problem..
here: https://forum.cfx.re/t/free-addon-11-gangsign-animations-by-mikey/4806838/7

**Comment by icecubepiso** [comment]
and its also in that commit

**Comment by BombayV** [comment]
@icecubepiso Two things.
1) It doesn't seem like you added Ultra's ycd files for the animations. I already got permission from him so just make sure to add them.
2) Do you mind asking for permission to the Divine guy just to make sure there are no issues with me merging this,

**Comment by icecubepiso** [comment]
1) it is possibel i forgor
2) i tough, if this is free i can just use it you know.. and there is a credits in readme so.. ye

**Pull request merged**
